source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

xcodeproj 'PMTweenTests.xcodeproj'

target :PMTweenTests, :exclusive => true do
  pod 'Specta', '~> 1.0.5'
  pod 'Expecta', '~> 1.0.5'
end