source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'

xcodeproj 'PMTweenTests.xcodeproj'

target :PMTweenTests, :exclusive => true do
  pod 'Specta', '~> 0.4'
  pod 'Expecta', '~> 0.3.2'
end